"""Added Genie Quests, task descriptions, and completion notes

Revision ID: 3a5e2a46d070
Revises: f0a6b97f9df6
Create Date: 2026-02-22 01:46:49.259111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a5e2a46d070'
down_revision = 'f0a6b97f9df6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_genie_quest', sa.Boolean(), nullable=True))

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_genie_task', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('completion_notes', sa.Text(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_used_free_wish', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('genie_wishes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_wish_reset', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_genie_evaluation', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_genie_evaluation')
        batch_op.drop_column('last_wish_reset')
        batch_op.drop_column('genie_wishes')
        batch_op.drop_column('has_used_free_wish')

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('completion_notes')
        batch_op.drop_column('is_genie_task')
        batch_op.drop_column('description')

    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.drop_column('is_genie_quest')

    # ### end Alembic commands ###
