"""Add email column

Revision ID: 4de25ebc1d5d
Revises: fe3f182804bb
Create Date: 2026-02-03 10:39:11.649598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4de25ebc1d5d'
down_revision = 'fe3f182804bb'
branch_labels = None
depends_on = None


def upgrade():
    # ... other code ...
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=150), nullable=True))
        batch_op.create_unique_constraint('uq_user_email', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
