"""Add completed column

Revision ID: 65b73c6e5f43
Revises: 
Create Date: 2026-01-09 22:50:19.142169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65b73c6e5f43'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed', sa.Boolean(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               nullable=True)
        batch_op.alter_column('difficulty',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('stat_type',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.drop_column('reminder_time')
        batch_op.drop_column('current_streak')
        batch_op.drop_column('target_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('current_streak', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('reminder_time', sa.VARCHAR(length=10), nullable=True))
        batch_op.alter_column('stat_type',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('difficulty',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('completed')

    # ### end Alembic commands ###
