"""added penalty zone to user

Revision ID: b0fa225c35eb
Revises: b89e10898107
Create Date: 2026-03-12 00:51:23.561847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0fa225c35eb'
down_revision = 'b89e10898107'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('in_penalty_zone', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('penalty_task', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('penalty_proof_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('penalty_proof_path')
        batch_op.drop_column('penalty_task')
        batch_op.drop_column('in_penalty_zone')

    # ### end Alembic commands ###
